language: python
python:
 - "2.7"

notifications:
    email: false

install:
    - pip install -r requirements/local.txt
    - pip install coveralls

script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
    - coverage run --source=. fabric_bolt/manage.py test --settings=fabric_bolt.core.settings.test

after_success:
    - coveralls
