language: python
python:
 - "2.7"

notifications:
    email: false

install:
    - pip install -r requirements/local.txt
    - pip install coveralls

script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
    - python fabric_bolt/manage.py syncdb --settings=fabric_bolt.core.settings.test
    - python fabric_bolt/manage.py migrate --settings=fabric_bolt.core.settings.test
    - python fabric_bolt/manage.py test projects hosts accounts --settings=fabric_bolt.core.settings.test
    - coverage run --source=. --omit=*/migrations/* fabric_bolt/manage.py test --settings=fabric_bolt.core.settings.test

after_success:
    - coveralls
